# Site settings
name: Jade D'Souza
title: Project 1 Proposal
url: https://info340c-sp21.github.io/project-1-pairs-wenyiz4/
baseurl: ''
email: jadedsouza@hotmail.com
cover: 
logo: 
resume:
social:
  - title: email
    url: mailto:jadedsouza@hotmail.com
  - title: instagram
    url: https://instagram.com/jadedsouza
  - title: github
    url: https://github.com/jadedsouza
  - title: linkedin
    url: https://www.linkedin.com/in/jadedsouza

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap

theme: jekyll-theme-hacker
